# Generated by Django 6.0.7 on 2026-08-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_lead',
            field=models.BooleanField(default=False),
        ),
    ]
