# Generated by Django 6.0.7 on 2026-08-11 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_lead',
        ),
    ]
