# Import Django REST Framework serializers
from rest_framework import serializers

# Import ContentType for GenericForeignKey
from django.contrib.contenttypes.models import ContentType

# Import Note model
from .models import Note

# Import Activity model
from apps.activities.activity.models import Activity


# Serializer for Note model
class NoteSerializer(serializers.ModelSerializer):

    # ---------------------------------------------------------
    # CRM MODULE
    # ---------------------------------------------------------
    # Return the CRM module name
    # Example: company, lead, deal, ticket
    module = serializers.SerializerMethodField()

    # ---------------------------------------------------------
    # ACTIVITY INFORMATION
    # ---------------------------------------------------------
    # Return the related Activity ID
    activity_id = serializers.IntegerField(
        source="activity.id",
        read_only=True
    )

    # Return the CRM object's ID from Activity
    object_id = serializers.IntegerField(
        source="activity.object_id",
        read_only=True
    )

    # ---------------------------------------------------------
    # CREATED BY USER INFORMATION
    # ---------------------------------------------------------
    # Return details of the user who created the Note
    created_by = serializers.SerializerMethodField()

    class Meta:

        # Model used by this serializer
        model = Note

        # Fields returned by the API
        fields = [
            "id",
            "activity_id",
            "module",
            "object_id",
            "content",
            "created_by",
            "created_at",
            "updated_at",
        ]

        # Fields generated by the backend
        read_only_fields = [
            "id",
            "activity_id",
            "module",
            "object_id",
            "created_by",
            "created_at",
            "updated_at",
        ]

    # ---------------------------------------------------------
    # GET CRM MODULE
    # ---------------------------------------------------------
    # Get the CRM module name from Activity ContentType
    def get_module(self, obj):

        return obj.activity.content_type.model

    # ---------------------------------------------------------
    # GET CREATED BY USER
    # ---------------------------------------------------------
    # Get the user who created the Note
    # The user is stored in Activity.created_by
    def get_created_by(self, obj):

        # Get the user from the related Activity
        user = obj.activity.created_by

        # If there is no user, return None
        if not user:
            return None

        # Return useful user details
        return {
            "id": user.id,
            "name": user.get_full_name() or user.email,
            "email": user.email,
        }

    # ---------------------------------------------------------
    # VALIDATE NOTE DATA
    # ---------------------------------------------------------
    def validate(self, attrs):

        # ---------------------------------------------------------
        # UPDATE SECTION
        # ---------------------------------------------------------
        # If self.instance exists, this is an update operation.
        # We don't require module/object_id again because the
        # existing Activity relationship is already available.
        if self.instance:

            return attrs

        # ---------------------------------------------------------
        # CREATE SECTION
        # ---------------------------------------------------------

        # Get module from request data
        module = self.initial_data.get("module")

        # Get CRM object ID from request data
        object_id = self.initial_data.get("object_id")

        # CRM modules supported by GenericForeignKey
        allowed_modules = [
            "lead",
            "deal",
            "company",
            "ticket",
        ]

        # Check module
        if not module:

            raise serializers.ValidationError({
                "module": "This field is required."
            })

        # Convert module to lowercase
        module = module.lower()

        # Check whether module is supported
        if module not in allowed_modules:

            raise serializers.ValidationError({
                "module": f"Choose one of: {allowed_modules}"
            })

        # Check object ID
        if not object_id:

            raise serializers.ValidationError({
                "object_id": "This field is required."
            })

        # Find ContentType for the selected CRM module
        try:

            content_type = ContentType.objects.get(
                model=module
            )

        except ContentType.DoesNotExist:

            raise serializers.ValidationError({
                "module": f"No model found for module '{module}'."
            })

        # Store ContentType temporarily
        # It will be used when creating Activity
        attrs["content_type"] = content_type

        # Store CRM object ID temporarily
        attrs["object_id"] = object_id

        return attrs

    # ---------------------------------------------------------
    # CREATE ACTIVITY AND NOTE
    # ---------------------------------------------------------
    def create(self, validated_data):

        # Get current request
        request = self.context.get("request")

        # Remove Activity-related data from Note data
        content_type = validated_data.pop("content_type")
        object_id = validated_data.pop("object_id")

        # Create Activity
        activity = Activity.objects.create(
            activity_type="note",

            # Set logged-in user as creator
            created_by=(
                request.user
                if request and request.user.is_authenticated
                else None
            ),

            # GenericForeignKey information
            content_type=content_type,
            object_id=object_id,
        )

        # Create Note linked to Activity
        note = Note.objects.create(
            activity=activity,
            **validated_data
        )

        return note