# Generated by Django 6.0.7 on 2026-08-18 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_annual_revenue_company_employees_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelTable(
            name='company',
            table='companies',
        ),
    ]
