# Generated by Django 6.0.7 on 2026-08-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_options_company_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='owner',
            new_name='company_owner',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='employees',
            new_name='no_of_employees',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company_type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='company',
            name='website',
        ),
        migrations.AlterField(
            model_name='company',
            name='domain_name',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
