# Generated by Django 6.0.7 on 2026-08-20 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_rename_name_company_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='lifecycle_stage',
        ),
    ]
