# Generated by Django 6.0.7 on 2026-08-19 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_options_alter_company_table'),
        ('companies', '0004_rename_name_company_company_name_and_more'),
    ]

    operations = [
    ]
