# Generated by Django 6.0.7 on 2026-08-21 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_merge_20260819_1101'),
        ('companies', '0005_remove_company_lifecycle_stage'),
    ]

    operations = [
    ]
