# Generated by Django 6.0.7 on 2026-08-23 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_merge_20260821_1108'),
        ('companies', '0006_merge_20260821_1603'),
    ]

    operations = [
    ]
