# Generated by Django 6.0.7 on 2026-08-31 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_rename_created_at_to_created_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-created_date']},
        ),
    ]
