# Generated by Django 6.0.7 on 2026-08-27 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_merge_20260821_0427'),
        ('companies', '0008_rename_created_at_to_created_date'),
    ]

    operations = [
    ]
