# Generated by Django 6.0.7 on 2026-08-27 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_merge_20260827_1304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-created_date']},
        ),
    ]
