# Generated by Django 6.0.7 on 2026-09-01 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_alter_company_options'),
        ('companies', '0010_alter_company_options'),
    ]

    operations = [
    ]
