# Generated by Django 6.0.7 on 2026-09-02 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_merge_20260831_1633'),
        ('companies', '0011_merge_20260901_2314'),
    ]

    operations = [
    ]
