# Generated by Django 6.0.7 on 2026-08-20 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='content',
            new_name='note',
        ),
    ]
