# Generated by Django 6.0.7 on 2026-08-07 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('CRM Software', 'CRM Software'), ('Marketing Tools', 'Marketing Tools'), ('Analytics Tools', 'Analytics Tools')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('job_title', models.CharField(max_length=100)),
                ('contact_owner', models.CharField(choices=[('Admin', 'Admin'), ('Sales', 'Sales'), ('Manager', 'Manager')], max_length=20)),
                ('lead_status', models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Closed', 'Closed'), ('Open', 'Open')], default='New', max_length=30)),
                ('company_type', models.CharField(choices=[('Startup', 'Startup'), ('Enterprise', 'Enterprise'), ('Private', 'Private'), ('Public', 'Public')], max_length=30)),
                ('city', models.CharField(choices=[('Dubai', 'Dubai'), ('Abu Dhabi', 'Abu Dhabi')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lead', to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(blank=True, related_name='leads', to='leads.product')),
            ],
        ),
    ]
