# Generated by Django 6.0.7 on 2026-08-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_status',
            field=models.CharField(choices=[('New', 'New'), ('Open', 'Open'), ('In Progress', 'In Progress'), ('Appointment Scheduled', 'Appointment Scheduled'), ('Presentation Scheduled', 'Presentation Scheduled'), ('Qualified to Buy', 'Qualified to Buy'), ('Contract Sent', 'Contract Sent'), ('Decision Maker Bought In', 'Decision Maker Bought In'), ('Closed Won', 'Closed Won'), ('Closed Lost', 'Closed Lost')], default='New', max_length=30),
        ),
    ]
