# Generated by Django 6.0.7 on 2026-08-22 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_email_alter_lead_lead_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='created_at',
            new_name='created_date',
        ),
    ]
