# Generated by Django 6.0.7 on 2026-09-01 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_merge_20260901_2314'),
        ('leads', '0004_remove_lead_company_type_lead_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_leads', to='companies.company'),
        ),
    ]
