# Generated by Django 6.0.7 on 2026-08-25 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_update_ticket_fields'),
        ('tickets', '0004_alter_ticket_associated_deal'),
    ]

    operations = [
    ]
