# Generated by Django 6.0.7 on 2026-08-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('email', 'Email'), ('note', 'Note'), ('call', 'Call'), ('task', 'Task'), ('meeting', 'Meeting')], max_length=20),
        ),
    ]
