# Generated by Django 6.0.7 on 2026-08-23 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_alter_activity_activity_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='activity',
            name='activity_ac_content_537ef7_idx',
        ),
        migrations.RemoveIndex(
            model_name='activity',
            name='activity_ac_activit_b6e897_idx',
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('email', 'Email'), ('note', 'Note'), ('call', 'Call'), ('task', 'Task'), ('meeting', 'Meeting')], max_length=20),
        ),
        migrations.AlterField(
            model_name='activity',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activity',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
    ]
