# Generated by Django 6.0.7 on 2026-08-18 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('related_module', models.CharField(choices=[('LEAD', 'Lead'), ('DEAL', 'Deal'), ('COMPANY', 'Company'), ('TICKET', 'Ticket')], max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('reminder', models.CharField(blank=True, choices=[('5_MIN', '5 minutes before'), ('15_MIN', '15 minutes before'), ('30_MIN', '30 minutes before'), ('1_HOUR', '1 hour before'), ('1_DAY', '1 day before')], max_length=20, null=True)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendees', models.ManyToManyField(blank=True, related_name='meeting_attendees', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
