# # Generated by Django 6.0.7 on 2026-08-31 19:20

# from django.db import migrations


# class Migration(migrations.Migration):

#     dependencies = [
#         ('meeting', '0001_initial'),
#     ]

#     operations = [
#     ]


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meeting", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE meeting_meeting
                DROP COLUMN IF EXISTS activity_type;
            """,
            reverse_sql="""
                ALTER TABLE meeting_meeting
                ADD COLUMN activity_type varchar(20) NOT NULL DEFAULT 'meeting';
            """,
        ),
    ]