# # Generated by Django 6.0.7 on 2026-08-31 14:01

# from django.db import migrations


# class Migration(migrations.Migration):

#     dependencies = [
#         ('meeting', '0002_meeting_activity'),
#     ]

#     operations = [
#     ]


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meeting", "0002_meeting_activity"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE meeting_meeting
                ADD COLUMN IF NOT EXISTS content_type_id bigint;

                ALTER TABLE meeting_meeting
                ADD COLUMN IF NOT EXISTS object_id integer;
            """,
            reverse_sql="""
                ALTER TABLE meeting_meeting
                DROP COLUMN IF EXISTS content_type_id;

                ALTER TABLE meeting_meeting
                DROP COLUMN IF EXISTS object_id;
            """,
        ),
    ]