# Generated by Django 6.0.7 on 2026-08-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_remove_meeting_object_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='activity_type',
            field=models.CharField(choices=[('MEETING', 'Meeting')], default='MEETING', max_length=20),
        ),
        migrations.AddField(
            model_name='meeting',
            name='module',
            field=models.CharField(blank=True, choices=[('LEAD', 'Lead'), ('DEAL', 'Deal'), ('COMPANY', 'Company'), ('TICKET', 'Ticket')], max_length=20, null=True),
        ),
    ]
