# Generated by Django 6.0.7 on 2026-08-31 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meeting", "0003_add_content_type_column"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE meeting_meeting
                ADD COLUMN IF NOT EXISTS object_id integer;
            """,
            reverse_sql="""
                ALTER TABLE meeting_meeting
                DROP COLUMN IF EXISTS object_id;
            """,
        ),
    ]