# Generated by Django 6.0.7 on 2026-08-31 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0004_fix_missing_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='object_id',
        ),
    ]
