# Generated by Django 6.0.7 on 2026-08-19 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0002_alter_activity_activity_type'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connected_object_id', models.PositiveBigIntegerField()),
                ('call_outcome', models.CharField(choices=[('connected', 'Connected'), ('no_answer', 'No Answer'), ('busy', 'Busy'), ('left_voicemail', 'Left Voicemail'), ('wrong_number', 'Wrong Number'), ('callback_requested', 'Callback Requested'), ('not_interested', 'Not Interested'), ('other', 'Other')], max_length=50)),
                ('call_date', models.DateField()),
                ('call_time', models.TimeField()),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='call', to='activity.activity')),
                ('connected_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_calls', to='contenttypes.contenttype')),
            ],
        ),
    ]
