# Generated by Django 6.0.7 on 2026-08-20 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='call',
            old_name='call_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='call',
            old_name='call_time',
            new_name='time',
        ),
    ]
