# Generated by Django 6.0.7 on 2026-09-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0002_rename_call_date_call_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
