# Generated by Django 6.0.7 on 2026-08-13 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_name', models.CharField(max_length=200)),
                ('deal_stage', models.CharField(choices=[('Contract Sent', 'Contract Sent'), ('Appointment Scheduled', 'Appointment Scheduled'), ('Presentation Scheduled', 'Presentation Scheduled'), ('Qualified to Buy', 'Qualified to Buy'), ('Closed Won', 'Closed Won'), ('Closed Lost', 'Closed Lost'), ('Decision Maker Bought In', 'Decision Maker Bought In')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('close_date', models.DateField()),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('associated_lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='associated_deals', to='leads.lead')),
                ('deal_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_deals', to='leads.lead')),
            ],
        ),
    ]
