# Generated by Django 6.0.7 on 2026-08-22 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_alter_deal_deal_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deal',
            old_name='created_at',
            new_name='created_date',
        ),
    ]
