# Generated by Django 6.0.7 on 2026-08-31 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_rename_created_at_deal_created_date'),
        ('leads', '0004_remove_lead_company_type_lead_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='associated_lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_deals', to='leads.lead'),
        ),
    ]
