# Generated by Django 6.0.7 on 2026-09-01 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='task',
            name='object_id',
        ),
    ]
