# """
# Django settings for config project.

# Generated by 'django-admin startproject' using Django 6.0.7.

# For more information on this file, see
# https://docs.djangoproject.com/en/6.0/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/6.0/ref/settings/
# """

# from pathlib import Path

# from decouple import config

# from datetime import timedelta


# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent


# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!


# # SECRET_KEY = 'django-insecure-o0+8m2^23vcnrjh%qnrii&sq=)h&i3^4cfu-9__o*x4@v&#f2a'
# SECRET_KEY = config("SECRET_KEY")

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = config("DEBUG", cast=bool)





# # ALLOWED_HOSTS = []


# ROOT_URLCONF = "config.urls"


# # Application definition

# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
    
#     # Third-party
#     "rest_framework",
#     "rest_framework_simplejwt.token_blacklist",
#     "corsheaders",

#     # Local Apps
#     'apps.accounts',
#     'apps.companies',
#     "apps.leads",
   
#     "apps.deals",
#     "apps.tickets",
#     "apps.dashboard",
#     "apps.notifications",
#     "apps.search",

# # Activity apps
#     "apps.activities.activity",
#     "apps.activities.note",
#     "apps.activities.call",
#     "apps.activities.email",
#     "apps.activities.meeting",
#     "apps.activities.task",
 
# ]

# MIDDLEWARE = [
#     "corsheaders.middleware.CorsMiddleware",
   
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# ]





# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:5173",
#     "http://127.0.0.1:5173",
#     "https://crm-frontend-s67r.onrender.com",
    
# ]

# ALLOWED_HOSTS = [
#     "crm-backend-8qts.onrender.com",
#     "localhost",
#     "127.0.0.1",
# ]




# ROOT_URLCONF = 'config.urls'

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = 'config.wsgi.application'


# # Database
# # https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME':  config("DB_NAME"),
#         'USER': config("DB_USER"),
#         'PASSWORD': config("DB_PASSWORD"),
#         'HOST': config("DB_HOST"),
#         'PORT': config("DB_PORT"),
#         'OPTIONS': {
#             'sslmode': 'require',
#         },
#     }
# }

# #  Email Configuration
# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

# # EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# EMAIL_HOST = config("EMAIL_HOST")
# EMAIL_PORT = config("EMAIL_PORT", cast=int)
# EMAIL_HOST_USER = config("EMAIL_HOST_USER")
# EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")
# EMAIL_USE_TLS = config("EMAIL_USE_TLS", cast=bool)


# DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL")

# FRONTEND_URL = config("FRONTEND_URL")


# # Password validation
# # https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# # Internationalization
# # https://docs.djangoproject.com/en/6.0/topics/i18n/

# LANGUAGE_CODE = 'en-us'


# USE_I18N = True


# TIME_ZONE = "Asia/Dubai"
# USE_TZ = True

# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/6.0/howto/static-files/

# STATIC_URL = 'static/'

# AUTH_USER_MODEL = "accounts.User"


# REST_FRAMEWORK = {
#     "DEFAULT_AUTHENTICATION_CLASSES": (
#         "rest_framework_simplejwt.authentication.JWTAuthentication",
#     ),
#     "DEFAULT_PERMISSION_CLASSES": (
#         "rest_framework.permissions.IsAuthenticated",
#     ),
# }

# SIMPLE_JWT = {
#     # "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),

#     "ACCESS_TOKEN_LIFETIME": timedelta(days=7),
#     "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
# }





# # ============================================================
# # TWILIO CONFIGURATION
# # ============================================================

# TWILIO_ACCOUNT_SID = config(
#     "TWILIO_ACCOUNT_SID",
#     default=None,
# )

# TWILIO_AUTH_TOKEN = config(
#     "TWILIO_AUTH_TOKEN",
#     default=None,
# )

# TWILIO_PHONE_NUMBER = config(
#     "TWILIO_PHONE_NUMBER",
#     default=None,
# )

# TWILIO_WEBHOOK_BASE_URL = config(
#     "TWILIO_WEBHOOK_BASE_URL",
#     default=None,
# )



# CSRF_TRUSTED_ORIGINS = [
#     "http://localhost:5173",
#     "http://127.0.0.1:5173",
#     "https://crm-frontend-s67r.onrender.com",
# ]


# ALLOWED_HOSTS = [
#     "crm-backend-8qts.onrender.com",
#     "localhost",
#     "127.0.0.1",
# ]








# """
# Django settings for config project.

# Generated by 'django-admin startproject' using Django 6.0.7.

# For more information on this file, see
# https://docs.djangoproject.com/en/6.0/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/6.0/ref/settings/
# """

# from pathlib import Path
# from datetime import timedelta

# from decouple import config


# # ============================================================
# # BASE DIRECTORY
# # ============================================================

# BASE_DIR = Path(__file__).resolve().parent.parent


# # ============================================================
# # SECURITY
# # ============================================================

# SECRET_KEY = config("SECRET_KEY")

# DEBUG = config("DEBUG", cast=bool)


# # ============================================================
# # ROOT URL CONFIGURATION
# # ============================================================

# ROOT_URLCONF = "config.urls"


# # ============================================================
# # ALLOWED HOSTS
# # ============================================================

# ALLOWED_HOSTS = [
#     "crm-backend-8qts.onrender.com",
#     "localhost",
#     "127.0.0.1",
# ]


# # ============================================================
# # APPLICATIONS
# # ============================================================

# INSTALLED_APPS = [
#     # Django apps
#     "django.contrib.admin",
#     "django.contrib.auth",
#     "django.contrib.contenttypes",
#     "django.contrib.sessions",
#     "django.contrib.messages",
#     "django.contrib.staticfiles",

#     # Third-party apps
#     "rest_framework",
#     "rest_framework_simplejwt.token_blacklist",
#     "corsheaders",

#     # Local apps
#     "apps.accounts",
#     "apps.companies",
#     "apps.leads",
#     "apps.deals",
#     "apps.tickets",
#     "apps.dashboard",
#     "apps.notifications",
#     "apps.search",

#     # Activity apps
#     "apps.activities.activity",
#     "apps.activities.note",
#     "apps.activities.call",
#     "apps.activities.email",
#     "apps.activities.meeting",
#     "apps.activities.task",
# ]


# # ============================================================
# # MIDDLEWARE
# # ============================================================

# MIDDLEWARE = [
#     # IMPORTANT:
#     # CorsMiddleware must be before CommonMiddleware
#     "corsheaders.middleware.CorsMiddleware",

#     "django.middleware.security.SecurityMiddleware",
#     "django.contrib.sessions.middleware.SessionMiddleware",
#     "django.middleware.common.CommonMiddleware",
#     "django.middleware.csrf.CsrfViewMiddleware",
#     "django.contrib.auth.middleware.AuthenticationMiddleware",
#     "django.contrib.messages.middleware.MessageMiddleware",
#     "django.middleware.clickjacking.XFrameOptionsMiddleware",
# ]


# # ============================================================
# # CORS CONFIGURATION
# # ============================================================

# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:5173",
#     "http://127.0.0.1:5173",

#     # Render frontend
#     "https://crm-frontend-s67r.onrender.com",
# ]


# # ============================================================
# # CSRF TRUSTED ORIGINS
# # ============================================================

# CSRF_TRUSTED_ORIGINS = [
#     "http://localhost:5173",
#     "http://127.0.0.1:5173",

#     # Render frontend
#     "https://crm-frontend-s67r.onrender.com",
# ]


# # ============================================================
# # TEMPLATES
# # ============================================================

# TEMPLATES = [
#     {
#         "BACKEND": "django.template.backends.django.DjangoTemplates",
#         "DIRS": [],
#         "APP_DIRS": True,
#         "OPTIONS": {
#             "context_processors": [
#                 "django.template.context_processors.request",
#                 "django.contrib.auth.context_processors.auth",
#                 "django.contrib.messages.context_processors.messages",
#             ],
#         },
#     },
# ]


# # ============================================================
# # WSGI
# # ============================================================

# WSGI_APPLICATION = "config.wsgi.application"


# # ============================================================
# # DATABASE
# # ============================================================

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.postgresql",
#         "NAME": config("DB_NAME"),
#         "USER": config("DB_USER"),
#         "PASSWORD": config("DB_PASSWORD"),
#         "HOST": config("DB_HOST"),
#         "PORT": config("DB_PORT"),
#         "OPTIONS": {
#             "sslmode": "require",
#         },
#     }
# }


# # ============================================================
# # EMAIL CONFIGURATION
# # ============================================================

# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

# # For local testing only, you can temporarily use:
# # EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# EMAIL_HOST = config("EMAIL_HOST")
# EMAIL_PORT = config("EMAIL_PORT", cast=int)
# EMAIL_HOST_USER = config("EMAIL_HOST_USER")
# EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")
# EMAIL_USE_TLS = config("EMAIL_USE_TLS", cast=bool)

# DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL")


# # ============================================================
# # FRONTEND URL
# # ============================================================

# FRONTEND_URL = config("FRONTEND_URL")


# # ============================================================
# # PASSWORD VALIDATION
# # ============================================================

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         "NAME": (
#             "django.contrib.auth.password_validation."
#             "UserAttributeSimilarityValidator"
#         ),
#     },
#     {
#         "NAME": (
#             "django.contrib.auth.password_validation."
#             "MinimumLengthValidator"
#         ),
#     },
#     {
#         "NAME": (
#             "django.contrib.auth.password_validation."
#             "CommonPasswordValidator"
#         ),
#     },
#     {
#         "NAME": (
#             "django.contrib.auth.password_validation."
#             "NumericPasswordValidator"
#         ),
#     },
# ]


# # ============================================================
# # INTERNATIONALIZATION
# # ============================================================

# LANGUAGE_CODE = "en-us"

# TIME_ZONE = "Asia/Dubai"

# USE_I18N = True

# USE_TZ = True


# # ============================================================
# # STATIC FILES
# # ============================================================

# STATIC_URL = "static/"


# # ============================================================
# # CUSTOM USER MODEL
# # ============================================================

# AUTH_USER_MODEL = "accounts.User"


# # ============================================================
# # DJANGO REST FRAMEWORK
# # ============================================================

# REST_FRAMEWORK = {
#     "DEFAULT_AUTHENTICATION_CLASSES": (
#         "rest_framework_simplejwt.authentication.JWTAuthentication",
#     ),

#     "DEFAULT_PERMISSION_CLASSES": (
#         "rest_framework.permissions.IsAuthenticated",
#     ),
# }


# # ============================================================
# # SIMPLE JWT
# # ============================================================

# SIMPLE_JWT = {
#     "ACCESS_TOKEN_LIFETIME": timedelta(days=7),
#     "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
# }


# # ============================================================
# # TWILIO CONFIGURATION
# # ============================================================

# TWILIO_ACCOUNT_SID = config(
#     "TWILIO_ACCOUNT_SID",
#     default=None,
# )

# TWILIO_AUTH_TOKEN = config(
#     "TWILIO_AUTH_TOKEN",
#     default=None,
# )

# TWILIO_PHONE_NUMBER = config(
#     "TWILIO_PHONE_NUMBER",
#     default=None,
# )

# TWILIO_WEBHOOK_BASE_URL = config(
#     "TWILIO_WEBHOOK_BASE_URL",
#     default=None,
# )




"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.
"""

from pathlib import Path
from datetime import timedelta

from decouple import config


# ============================================================
# BASE
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# ============================================================
# SECURITY
# ============================================================

SECRET_KEY = config("SECRET_KEY")

DEBUG = config("DEBUG", cast=bool, default=False)


# ============================================================
# HOSTS
# ============================================================

ALLOWED_HOSTS = [
    "crm-backend-8qts.onrender.com",
    "localhost",
    "127.0.0.1",
]


# ============================================================
# APPLICATIONS
# ============================================================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third party
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",

    # CRM apps
    "apps.accounts",
    "apps.companies",
    "apps.leads",
    "apps.deals",
    "apps.tickets",
    "apps.dashboard",
    "apps.notifications",
    "apps.search",

    # Activities
    "apps.activities.activity",
    "apps.activities.note",
    "apps.activities.call",
    "apps.activities.email",
    "apps.activities.meeting",
    "apps.activities.task",

    "apps.ai",
]


# ============================================================
# MIDDLEWARE
# ============================================================

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",

    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# ============================================================
# CORS
# ============================================================

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "https://crm-frontend-s67r.onrender.com",
]


# ============================================================
# CSRF
# ============================================================

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "https://crm-frontend-s67r.onrender.com",
]


# ============================================================
# URL / WSGI
# ============================================================

ROOT_URLCONF = "config.urls"

WSGI_APPLICATION = "config.wsgi.application"


# ============================================================
# TEMPLATES
# ============================================================

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# ============================================================
# DATABASE
# ============================================================

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("DB_NAME"),
        "USER": config("DB_USER"),
        "PASSWORD": config("DB_PASSWORD"),
        "HOST": config("DB_HOST"),
        "PORT": config("DB_PORT"),
        "OPTIONS": {
            "sslmode": "require",
        },
    }
}


# ============================================================
# RESEND EMAIL
# ============================================================
#
# IMPORTANT:
# We are NOT using Gmail SMTP anymore.
#
# Resend uses HTTPS API, so Render does not need to connect
# directly to smtp.gmail.com:587.
#

RESEND_API_KEY = config("RESEND_API_KEY")

RESEND_FROM_EMAIL = config(
    "RESEND_FROM_EMAIL",
    default="onboarding@resend.dev",
)

DEFAULT_FROM_EMAIL = RESEND_FROM_EMAIL

FRONTEND_URL = config(
    "FRONTEND_URL",
    default="http://localhost:5173",
)


# ============================================================
# PASSWORD VALIDATORS
# ============================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME":
        "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
    },
    {
        "NAME":
        "django.contrib.auth.password_validation.MinimumLengthValidator"
    },
    {
        "NAME":
        "django.contrib.auth.password_validation.CommonPasswordValidator"
    },
    {
        "NAME":
        "django.contrib.auth.password_validation.NumericPasswordValidator"
    },
]


# ============================================================
# INTERNATIONALIZATION
# ============================================================

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Dubai"

USE_I18N = True

USE_TZ = True


# ============================================================
# STATIC
# ============================================================

STATIC_URL = "static/"


# ============================================================
# CUSTOM USER
# ============================================================

AUTH_USER_MODEL = "accounts.User"


# ============================================================
# DJANGO REST FRAMEWORK
# ============================================================

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),

    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
}


# ============================================================
# SIMPLE JWT
# ============================================================

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=7),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
}


# ============================================================
# TWILIO
# ============================================================

TWILIO_ACCOUNT_SID = config(
    "TWILIO_ACCOUNT_SID",
    default=None,
)

TWILIO_AUTH_TOKEN = config(
    "TWILIO_AUTH_TOKEN",
    default=None,
)

TWILIO_PHONE_NUMBER = config(
    "TWILIO_PHONE_NUMBER",
    default=None,
)

TWILIO_WEBHOOK_BASE_URL = config(
    "TWILIO_WEBHOOK_BASE_URL",
    default=None,
)




# OPENAI_API_KEY = config("OPENAI_API_KEY", default="")