# Generated by Django 6.0.7 on 2026-08-16 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activity_content_type_activity_object_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
